# Numpy

In [1]:
# Cargar el modulo numpy
import numpy as np

In [2]:
# Documentacion
help(np)

Output hidden; open in https://colab.research.google.com to view.

In [3]:
# Funcion dir : Listar los componentes del modulo
dir(np)

['ALLOW_THREADS',
 'BUFSIZE',
 'CLIP',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'WRAP',
 '_CopyMode',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__git_version__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_builtins',
 '_distribut

In [4]:
# Lista de elementos que compone al submodulo random
dir(np.random)

['BitGenerator',
 'Generator',
 'MT19937',
 'PCG64',
 'PCG64DXSM',
 'Philox',
 'RandomState',
 'SFC64',
 'SeedSequence',
 '__RandomState_ctor',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_bounded_integers',
 '_common',
 '_generator',
 '_mt19937',
 '_pcg64',
 '_philox',
 '_pickle',
 '_sfc64',
 'beta',
 'binomial',
 'bit_generator',
 'bytes',
 'chisquare',
 'choice',
 'default_rng',
 'dirichlet',
 'exponential',
 'f',
 'gamma',
 'geometric',
 'get_bit_generator',
 'get_state',
 'gumbel',
 'hypergeometric',
 'laplace',
 'logistic',
 'lognormal',
 'logseries',
 'mtrand',
 'multinomial',
 'multivariate_normal',
 'negative_binomial',
 'noncentral_chisquare',
 'noncentral_f',
 'normal',
 'pareto',
 'permutation',
 'poisson',
 'power',
 'rand',
 'randint',
 'randn',
 'random',
 'random_integers',
 'random_sample',
 'ranf',
 'rayleigh',
 'sample',
 'seed',
 'set_bit_generator',
 'set_state',
 'shuf

In [5]:
# Documentacion del submodulo random
help(np.random)

Help on package numpy.random in numpy:

NAME
    numpy.random

DESCRIPTION
    Random Number Generation
    
    Use ``default_rng()`` to create a `Generator` and call its methods.
    
    =============== =========================================================
    Generator
    --------------- ---------------------------------------------------------
    Generator       Class implementing all of the random number distributions
    default_rng     Default constructor for ``Generator``
    =============== =========================================================
    
    ============================================= ===
    BitGenerator Streams that work with Generator
    --------------------------------------------- ---
    MT19937
    PCG64
    PCG64DXSM
    Philox
    SFC64
    ============================================= ===
    
    ============================================= ===
    Getting entropy to initialize a BitGenerator
    --------------------------------------------

In [6]:
# Lista de elementos que componen al submodulo linalg
dir(np.linalg)

['LinAlgError',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_umath_linalg',
 'cholesky',
 'cond',
 'det',
 'eig',
 'eigh',
 'eigvals',
 'eigvalsh',
 'inv',
 'lapack_lite',
 'linalg',
 'lstsq',
 'matrix_power',
 'matrix_rank',
 'multi_dot',
 'norm',
 'pinv',
 'qr',
 'slogdet',
 'solve',
 'svd',
 'tensorinv',
 'tensorsolve',
 'test']

In [7]:
# Documentacion de la funcion cholesky
help(np.linalg.cholesky)

Help on _ArrayFunctionDispatcher in module numpy.linalg:

cholesky(a)
    Cholesky decomposition.
    
    Return the Cholesky decomposition, `L * L.H`, of the square matrix `a`,
    where `L` is lower-triangular and .H is the conjugate transpose operator
    (which is the ordinary transpose if `a` is real-valued).  `a` must be
    Hermitian (symmetric if real-valued) and positive-definite. No
    checking is performed to verify whether `a` is Hermitian or not.
    In addition, only the lower-triangular and diagonal elements of `a`
    are used. Only `L` is actually returned.
    
    Parameters
    ----------
    a : (..., M, M) array_like
        Hermitian (symmetric if all elements are real), positive-definite
        input matrix.
    
    Returns
    -------
    L : (..., M, M) array_like
        Lower-triangular Cholesky factor of `a`.  Returns a matrix object if
        `a` is a matrix object.
    
    Raises
    ------
    LinAlgError
       If the decomposition fails, for exam

# Primeros pasos usando Numpy

In [8]:
# Objeto principal de numpy : ndarray
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          like=None)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        ``__array__`` method returns an array, or any (nested) sequence.
        If object is a scalar, a 0-dimensional array containing object is
        returned.
    dtype : data-type, optional
        The desired data-type for the array. If not given, NumPy will try to use
        a default ``dtype`` that can represent the values (by applying promotion
        rules when necessary.)
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if ``__array__`` returns a copy, if obj is a nested
        sequence, or if a copy is needed to satisfy any of the other
        requirements (``dtype``, ``order``, e

In [9]:
# Definamos una lista
Lista1 = [12,13,24,3465,576,457,5678,567,56,765]
Vec1 = np.array(Lista1)
Vec1

array([  12,   13,   24, 3465,  576,  457, 5678,  567,   56,  765])

In [10]:
# tipo de Lista1
type(Lista1)

list

In [11]:
# Tipo de datos es Vec1
type(Vec1)

numpy.ndarray

In [12]:
# Lista de metodos/atributos que podemos aplicar a un dato de tipo numpy.ndarray
dir(Vec1)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__class_getitem__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__dlpack__',
 '__dlpack_device__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',

In [13]:
# Generemos un conjunto de notas aleatorias
import random as rnd
notas = []
for n in range(10000):
  notas.append(rnd.randint(0,20))

# Notas simuladas
notas

[15,
 13,
 0,
 19,
 18,
 12,
 5,
 1,
 20,
 18,
 6,
 19,
 5,
 15,
 8,
 17,
 8,
 11,
 3,
 4,
 2,
 15,
 9,
 7,
 9,
 3,
 1,
 6,
 9,
 19,
 0,
 3,
 19,
 13,
 5,
 8,
 16,
 4,
 10,
 11,
 19,
 20,
 20,
 8,
 11,
 11,
 18,
 10,
 19,
 9,
 17,
 7,
 2,
 17,
 20,
 16,
 2,
 3,
 1,
 20,
 17,
 12,
 15,
 3,
 20,
 20,
 12,
 8,
 2,
 16,
 13,
 13,
 20,
 3,
 6,
 11,
 18,
 3,
 16,
 18,
 14,
 4,
 0,
 16,
 8,
 18,
 18,
 16,
 5,
 15,
 6,
 11,
 15,
 13,
 20,
 11,
 20,
 4,
 2,
 6,
 9,
 18,
 18,
 9,
 5,
 3,
 9,
 2,
 11,
 20,
 12,
 4,
 2,
 10,
 10,
 4,
 7,
 2,
 13,
 3,
 10,
 8,
 9,
 2,
 10,
 2,
 2,
 8,
 19,
 8,
 8,
 1,
 8,
 3,
 19,
 12,
 17,
 0,
 20,
 16,
 7,
 7,
 3,
 19,
 17,
 2,
 8,
 2,
 6,
 8,
 3,
 9,
 13,
 8,
 4,
 16,
 5,
 6,
 6,
 20,
 6,
 9,
 0,
 20,
 10,
 14,
 14,
 18,
 10,
 5,
 10,
 1,
 20,
 11,
 16,
 20,
 3,
 1,
 16,
 13,
 19,
 4,
 11,
 15,
 3,
 12,
 6,
 6,
 18,
 5,
 11,
 7,
 2,
 1,
 17,
 14,
 0,
 5,
 4,
 11,
 19,
 11,
 1,
 1,
 7,
 18,
 16,
 9,
 13,
 9,
 9,
 3,
 12,
 13,
 2,
 20,
 0,
 17,
 11,
 11,
 2,
 7,
 

In [14]:
# El objeto notas lo puedo transformar a un objeto ndarray
notas = np.array(notas)

In [15]:
# np.array proviene de una lista
len(notas)

10000

In [16]:
# np.array proviene de una lista
sum(notas)

99940

In [17]:
# np.array proviene de una lista
promedioNotas = sum(notas)/len(notas)
promedioNotas

9.994

In [23]:
# Repliquemos 1000 veces el siguiente experimento : Generar un vector con 10000 notas

# Definamos una funcion que devuelve el vector de notas (10000 elementos)
def SimulNotas(Num = 10000):
  notas = []
  for i in range(Num):
    notas.append(rnd.randint(0,20))
  return np.array(notas)

# Ejecutemos la funcion SimulNotas un numero total de 1000 veces
# Y guardemos los promedios de estas 1000 ejecuciones
# Midamos el tiempo de esta ejecucion

Prom = list()

# Crear un directorio donde almacenaremos todos nuestros archivos simulados
import os
os.mkdir("TLC1")

# %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
import time
IniciaCronometro = time.time()
for exe  in range(1000):
  notas = SimulNotas()
  Promedio = sum(notas)/len(notas)
  # Guardemos estos promedios en una lista
  Prom.append(Promedio)
  # Guardemos en disco duro ese vector : Empezamos creando un nombre de archivo que diferencia a cada archivo generado
  nombre_archivo = "TLC1/"+ "Prom" + "iter" + str(exe) + ".txt"
  np.savetxt(nombre_archivo, Prom)

FinalizaCronometro = time.time()
# %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
# Calculemos la media de Prom
print("""
La media de 1000 ejecuciones es  : %.3f
Tiempo de ejecucion : %d
""" %(sum(Prom)/len(Prom), FinalizaCronometro-IniciaCronometro))


La media de 1000 ejecuciones es  : 10.000
Tiempo de ejecucion : 14



# Operaciones con objetos de tipo ndarray

In [24]:
# Ya sabemos que es un iterable
for elemento in np.array([12,4,2,9]):
  print(elemento**2)

144
16
4
81


In [26]:
# Acceso a los elementos de un adarray
# primer elemento de notas
notas[0]

0

In [27]:
# Ultimo elemento de notas
notas[-1]

14

In [28]:
# primeros 5 elementos de notas
notas[:5]

array([ 0,  7, 17, 14,  8])

In [29]:
# ultimos 8 elementos de notas
notas[-8:]

array([16,  2,  0, 10, 15,  9, 15, 14])

In [30]:
# del 10mo elemento al 20avo elemento de notas
notas[9:20]

array([ 8, 15,  2,  3,  0, 14, 10,  8,  1, 12, 11])

# Atributos informativos de un ndarray

In [31]:
# el atributo shape
notas.shape

(10000,)

In [32]:
# Documentacion de la funcion np.array
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          like=None)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        ``__array__`` method returns an array, or any (nested) sequence.
        If object is a scalar, a 0-dimensional array containing object is
        returned.
    dtype : data-type, optional
        The desired data-type for the array. If not given, NumPy will try to use
        a default ``dtype`` that can represent the values (by applying promotion
        rules when necessary.)
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if ``__array__`` returns a copy, if obj is a nested
        sequence, or if a copy is needed to satisfy any of the other
        requirements (``dtype``, ``order``, e

In [33]:
# El metodo ndim
notas.ndim

1

In [34]:
# El atributo size
notas.size

10000

In [35]:
# El metodo reshape
# Documentacion
help(notas.reshape)

Help on built-in function reshape:

reshape(...) method of numpy.ndarray instance
    a.reshape(shape, order='C')
    
    Returns an array containing the same data with a new shape.
    
    Refer to `numpy.reshape` for full documentation.
    
    See Also
    --------
    numpy.reshape : equivalent function
    
    Notes
    -----
    Unlike the free function `numpy.reshape`, this method on `ndarray` allows
    the elements of the shape parameter to be passed in as separate arguments.
    For example, ``a.reshape(10, 11)`` is equivalent to
    ``a.reshape((10, 11))``.



In [37]:
# MOdifiquemos la dimension del objeto notas
notas.reshape((1000, 10))

array([[ 0,  7, 17, ...,  8,  6,  8],
       [15,  2,  3, ...,  1, 12, 11],
       [ 0, 20, 16, ..., 15, 11, 13],
       ...,
       [11, 20,  4, ..., 12, 17, 16],
       [ 8, 10,  4, ..., 17, 18, 13],
       [ 6,  4, 16, ...,  9, 15, 14]])

In [38]:
notas

array([ 0,  7, 17, ...,  9, 15, 14])

In [39]:
# Documentacion de la funcion reshape de numpy
help(np.reshape)

Help on _ArrayFunctionDispatcher in module numpy:

reshape(a, newshape, order='C')
    Gives a new shape to an array without changing its data.
    
    Parameters
    ----------
    a : array_like
        Array to be reshaped.
    newshape : int or tuple of ints
        The new shape should be compatible with the original shape. If
        an integer, then the result will be a 1-D array of that length.
        One shape dimension can be -1. In this case, the value is
        inferred from the length of the array and remaining dimensions.
    order : {'C', 'F', 'A'}, optional
        Read the elements of `a` using this index order, and place the
        elements into the reshaped array using this index order.  'C'
        means to read / write the elements using C-like index order,
        with the last axis index changing fastest, back to the first
        axis index changing slowest. 'F' means to read / write the
        elements using Fortran-like index order, with the first index
 

In [40]:
np.reshape(notas , (1000, 10))

array([[ 0,  7, 17, ...,  8,  6,  8],
       [15,  2,  3, ...,  1, 12, 11],
       [ 0, 20, 16, ..., 15, 11, 13],
       ...,
       [11, 20,  4, ..., 12, 17, 16],
       [ 8, 10,  4, ..., 17, 18, 13],
       [ 6,  4, 16, ...,  9, 15, 14]])

# Cosas a practicas/estudiar/aprender
* Libro del profesor Carlos Chavez (Algebra Lineal)
* Teoria de la Probabilidad : Klenke
* Aprender a utilizar las funciones que se listan a continuacion

> empty_like : Return an empty array with shape and type of input.

> ones_like : Return an array of ones with shape and type of input.

> zeros_like : Return an array of zeros with shape and type of input.

> full_like : Return a new array with shape of input filled with value.

> empty : Return a new uninitialized array.

> ones : Return a new array setting values to one.

> zeros : Return a new array setting values to zero.

> full : Return a new array of given shape filled with value.
    

#  Submodulo random de numpy


In [41]:
# Documentacion
help(np.random)

Help on package numpy.random in numpy:

NAME
    numpy.random

DESCRIPTION
    Random Number Generation
    
    Use ``default_rng()`` to create a `Generator` and call its methods.
    
    =============== =========================================================
    Generator
    --------------- ---------------------------------------------------------
    Generator       Class implementing all of the random number distributions
    default_rng     Default constructor for ``Generator``
    =============== =========================================================
    
    ============================================= ===
    BitGenerator Streams that work with Generator
    --------------------------------------------- ---
    MT19937
    PCG64
    PCG64DXSM
    Philox
    SFC64
    ============================================= ===
    
    ============================================= ===
    Getting entropy to initialize a BitGenerator
    --------------------------------------------

In [42]:
# Elementos que componen al submodulo random
dir(np.random)

['BitGenerator',
 'Generator',
 'MT19937',
 'PCG64',
 'PCG64DXSM',
 'Philox',
 'RandomState',
 'SFC64',
 'SeedSequence',
 '__RandomState_ctor',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_bounded_integers',
 '_common',
 '_generator',
 '_mt19937',
 '_pcg64',
 '_philox',
 '_pickle',
 '_sfc64',
 'beta',
 'binomial',
 'bit_generator',
 'bytes',
 'chisquare',
 'choice',
 'default_rng',
 'dirichlet',
 'exponential',
 'f',
 'gamma',
 'geometric',
 'get_bit_generator',
 'get_state',
 'gumbel',
 'hypergeometric',
 'laplace',
 'logistic',
 'lognormal',
 'logseries',
 'mtrand',
 'multinomial',
 'multivariate_normal',
 'negative_binomial',
 'noncentral_chisquare',
 'noncentral_f',
 'normal',
 'pareto',
 'permutation',
 'poisson',
 'power',
 'rand',
 'randint',
 'randn',
 'random',
 'random_integers',
 'random_sample',
 'ranf',
 'rayleigh',
 'sample',
 'seed',
 'set_bit_generator',
 'set_state',
 'shuf

In [43]:
# Documentacion de la funcion uniform
help(np.random.uniform)

Help on built-in function uniform:

uniform(...) method of numpy.random.mtrand.RandomState instance
    uniform(low=0.0, high=1.0, size=None)
    
    Draw samples from a uniform distribution.
    
    Samples are uniformly distributed over the half-open interval
    ``[low, high)`` (includes low, but excludes high).  In other words,
    any value within the given interval is equally likely to be drawn
    by `uniform`.
    
    .. note::
        New code should use the `~numpy.random.Generator.uniform`
        method of a `~numpy.random.Generator` instance instead;
        please see the :ref:`random-quick-start`.
    
    Parameters
    ----------
    low : float or array_like of floats, optional
        Lower boundary of the output interval.  All values generated will be
        greater than or equal to low.  The default value is 0.
    high : float or array_like of floats
        Upper boundary of the output interval.  All values generated will be
        less than or equal to high

In [44]:
# Generemos una matriz de 10**3 x 10**3 elementos usando np.random.uniform
# low = 4, high = 12
mat1 = np.random.uniform(4, 12, (1000, 1000))

In [45]:
# Tipo
type(mat1)

numpy.ndarray

In [46]:
# Atributos informativos
mat1.ndim

2

In [47]:
# shape
mat1.shape

(1000, 1000)

In [49]:
# Documentacion del metodo min
help(mat1.min)

Help on built-in function min:

min(...) method of numpy.ndarray instance
    a.min(axis=None, out=None, keepdims=False, initial=<no value>, where=True)
    
    Return the minimum along a given axis.
    
    Refer to `numpy.amin` for full documentation.
    
    See Also
    --------
    numpy.amin : equivalent function



In [50]:
# Funcion amin de numpy : Documentacion
help(np.amin)

Help on _ArrayFunctionDispatcher in module numpy:

amin(a, axis=None, out=None, keepdims=<no value>, initial=<no value>, where=<no value>)
    Return the minimum of an array or minimum along an axis.
    
    `amin` is an alias of `~numpy.min`.
    
    See Also
    --------
    min : alias of this function
    ndarray.min : equivalent method



In [53]:
# El minimo para cada fila
np.amin(mat1, axis = 0)

array([4.00804617, 4.01674529, 4.00794542, 4.0093867 , 4.00176475,
       4.01708098, 4.00400799, 4.00532891, 4.0025976 , 4.01640381,
       4.00061367, 4.00137532, 4.00115638, 4.00334261, 4.0260151 ,
       4.02882742, 4.0008053 , 4.00018954, 4.00148365, 4.0044639 ,
       4.00647346, 4.00093669, 4.00719912, 4.00260283, 4.03703017,
       4.00405923, 4.00074968, 4.020659  , 4.00243334, 4.00464903,
       4.01526765, 4.00460054, 4.00322093, 4.00572626, 4.0180645 ,
       4.00020484, 4.00028422, 4.00625953, 4.00522896, 4.00152712,
       4.00589488, 4.00199656, 4.00656419, 4.00484403, 4.00363216,
       4.00335317, 4.01939159, 4.0062444 , 4.00386428, 4.00367107,
       4.00094146, 4.01251125, 4.00140867, 4.00229319, 4.00366046,
       4.00927922, 4.00082811, 4.0109346 , 4.00085827, 4.0208714 ,
       4.00003449, 4.0315414 , 4.00078018, 4.00298339, 4.00325204,
       4.00206777, 4.00453867, 4.00386828, 4.00415514, 4.00210578,
       4.01690945, 4.0102631 , 4.00198528, 4.01515581, 4.02601

In [54]:
# El minimo en la dimension de las columnas
np.amin(mat1, axis = 1)

array([4.01429384, 4.00063164, 4.00755919, 4.0005584 , 4.00199656,
       4.00285296, 4.03966392, 4.00816026, 4.00167023, 4.00723521,
       4.00094146, 4.01255879, 4.00237031, 4.00249769, 4.00002965,
       4.01502681, 4.00197252, 4.00051074, 4.005234  , 4.00289612,
       4.00897533, 4.00453681, 4.04703667, 4.0006155 , 4.00667327,
       4.00392009, 4.00147563, 4.00405525, 4.00192258, 4.00676932,
       4.00262343, 4.00091292, 4.01988064, 4.00253366, 4.00003287,
       4.00453024, 4.00374447, 4.01190677, 4.00118097, 4.00338108,
       4.00142572, 4.00594408, 4.0008561 , 4.00694621, 4.00045704,
       4.00839763, 4.00018355, 4.0044639 , 4.00106135, 4.01911319,
       4.01296698, 4.00021701, 4.01084214, 4.00192644, 4.01027433,
       4.01272134, 4.00025528, 4.00433789, 4.04355407, 4.00064241,
       4.00782472, 4.00760177, 4.00458774, 4.00090828, 4.00526223,
       4.00520022, 4.00371567, 4.0180645 , 4.00009728, 4.01036276,
       4.00000909, 4.00666079, 4.00272025, 4.01243038, 4.00912

In [55]:
# Documentacion de la funcion np.random.chisquare
help(np.random.chisquare)

Help on built-in function chisquare:

chisquare(...) method of numpy.random.mtrand.RandomState instance
    chisquare(df, size=None)
    
    Draw samples from a chi-square distribution.
    
    When `df` independent random variables, each with standard normal
    distributions (mean 0, variance 1), are squared and summed, the
    resulting distribution is chi-square (see Notes).  This distribution
    is often used in hypothesis testing.
    
    .. note::
        New code should use the `~numpy.random.Generator.chisquare`
        method of a `~numpy.random.Generator` instance instead;
        please see the :ref:`random-quick-start`.
    
    Parameters
    ----------
    df : float or array_like of floats
         Number of degrees of freedom, must be > 0.
    size : int or tuple of ints, optional
        Output shape.  If the given shape is, e.g., ``(m, n, k)``, then
        ``m * n * k`` samples are drawn.  If size is ``None`` (default),
        a single value is returned if ``df

In [56]:
# Generemos un objeto tridimensional con distribucion chisquare
mat2 = np.random.chisquare(12, (3,4,9))
mat2

array([[[19.35593379,  6.0646268 ,  9.14277463, 17.2208371 ,
          6.72639152, 12.99395076, 17.90600604, 25.29403628,
         10.32628415],
        [23.1180918 , 12.05424547, 10.21061102, 11.09849243,
         18.97786445,  8.60698464, 15.28446376, 10.33507038,
          5.1024569 ],
        [15.3357471 , 13.94136372, 20.95846636, 11.2547767 ,
          3.34423229, 24.79314723, 20.66064873, 15.10502868,
         12.70335102],
        [ 7.92209858, 12.74818081, 11.21188281, 18.22869422,
         15.92038486, 15.78737253, 17.13737727,  5.82305268,
          6.74304128]],

       [[12.82621724, 22.33634354,  6.04076752, 11.52606257,
         15.05421134, 10.90271014, 13.15110289, 13.46728971,
         14.38044537],
        [16.23780927,  3.80551537, 13.79035965,  8.91973686,
          7.29148848, 12.6358842 , 15.05953213, 11.12853369,
          5.05073819],
        [ 9.95755238, 13.3910397 , 19.80460791,  9.14725194,
          7.6285473 , 11.77143591, 12.56440837, 11.65140174,
      

In [58]:
# Obtengamos cada uno de las 3 matrices de 4x9
x1 = mat2[0,:,:]
x2 = mat2[1,:,:]
x3 = mat2[2,:,:]

In [59]:
# Primera fila de x3
x3[0,:]

array([12.98347818, 14.9114147 , 19.60672236, 11.02574365,  5.56266093,
        8.69692373, 12.30789476, 25.56067092, 14.51921516])

In [61]:
# Las operaciones con objetos de numpy son vectorizadas
x3-10

# A cada elemento de x3 le resta

array([[ 2.98347818,  4.9114147 ,  9.60672236,  1.02574365, -4.43733907,
        -1.30307627,  2.30789476, 15.56067092,  4.51921516],
       [ 3.90004921, 10.31936715,  0.91974079,  4.37550872,  0.92021357,
         2.37636343, -3.59817126,  2.22965326,  1.93535227],
       [-3.38748255, -0.01688458,  2.6765864 ,  5.37544248, -0.30987978,
         8.74617129, -0.42092056,  4.34467028,  6.07386899],
       [-3.35665946,  0.76365218,  2.83749037,  3.51325008,  0.02174806,
         2.71347149, -0.43695369, -5.14615161,  2.83152607]])

In [62]:
# La funcion seno de numpy
np.sin(x1)

# Las operaciones entre elementos de numpy son vectorizadas

array([[ 0.48501286, -0.21682265,  0.2782804 , -0.99832296,  0.4288381 ,
         0.41467002, -0.80964669,  0.16059658, -0.78426228],
       [-0.90310376, -0.49003085, -0.70741423, -0.9947086 ,  0.12795676,
         0.72963861,  0.41095331, -0.78968318, -0.92488324],
       [ 0.36368074,  0.98089171,  0.85867676, -0.96659471, -0.20125565,
        -0.3331043 ,  0.97126746,  0.56706206,  0.13655243],
       [ 0.99768094,  0.18081023, -0.97669639, -0.58173627, -0.21082768,
        -0.07932583, -0.99002216, -0.44406694,  0.44381904]])

In [63]:
# Comparacion
x3 == x2

# Operacion vectorizada

array([[False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False]])

In [64]:
# Detalles algebraicos
r1 = np.array([-1,0,1])/0
r1

<ipython-input-64-2def6d4b8682>:2: RuntimeWarning: divide by zero encountered in divide
  r1 = np.array([-1,0,1])/0
<ipython-input-64-2def6d4b8682>:2: RuntimeWarning: invalid value encountered in divide
  r1 = np.array([-1,0,1])/0


array([-inf,  nan,  inf])

In [65]:
# Documentacion de inf
help(np.inf)

Help on float object:

class float(object)
 |  float(x=0, /)
 |  
 |  Convert a string or number to a floating point number, if possible.
 |  
 |  Methods defined here:
 |  
 |  __abs__(self, /)
 |      abs(self)
 |  
 |  __add__(self, value, /)
 |      Return self+value.
 |  
 |  __bool__(self, /)
 |      True if self else False
 |  
 |  __ceil__(self, /)
 |      Return the ceiling as an Integral.
 |  
 |  __divmod__(self, value, /)
 |      Return divmod(self, value).
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __float__(self, /)
 |      float(self)
 |  
 |  __floor__(self, /)
 |      Return the floor as an Integral.
 |  
 |  __floordiv__(self, value, /)
 |      Return self//value.
 |  
 |  __format__(self, format_spec, /)
 |      Formats the float according to format_spec.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  __getnewargs__(self, /)
 |  
 |  __gt__(sel

In [66]:
# Documentacion de nan : not a number
help(np.nan)

Help on float object:

class float(object)
 |  float(x=0, /)
 |  
 |  Convert a string or number to a floating point number, if possible.
 |  
 |  Methods defined here:
 |  
 |  __abs__(self, /)
 |      abs(self)
 |  
 |  __add__(self, value, /)
 |      Return self+value.
 |  
 |  __bool__(self, /)
 |      True if self else False
 |  
 |  __ceil__(self, /)
 |      Return the ceiling as an Integral.
 |  
 |  __divmod__(self, value, /)
 |      Return divmod(self, value).
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __float__(self, /)
 |      float(self)
 |  
 |  __floor__(self, /)
 |      Return the floor as an Integral.
 |  
 |  __floordiv__(self, value, /)
 |      Return self//value.
 |  
 |  __format__(self, format_spec, /)
 |      Formats the float according to format_spec.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  __getnewargs__(self, /)
 |  
 |  __gt__(sel

In [69]:
A = np.random.randint(0,20, (5,5))

In [70]:
B = A+1

In [71]:
C = A*B
C
# El producto elemento a elemento

array([[240,  20,  72,  56,   0],
       [380, 110,  20,  20,   0],
       [ 72,  30,  20, 342,  30],
       [ 72,  30, 306, 132, 210],
       [156,   2,  30, 272,   0]])

In [73]:
# Producto matricial
help(np.matmul)

Help on ufunc:

matmul = <ufunc 'matmul'>
    matmul(x1, x2, /, out=None, *, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj, axes, axis])
    
    Matrix product of two arrays.
    
    Parameters
    ----------
    x1, x2 : array_like
        Input arrays, scalars not allowed.
    out : ndarray, optional
        A location into which the result is stored. If provided, it must have
        a shape that matches the signature `(n,k),(k,m)->(n,m)`. If not
        provided or None, a freshly-allocated array is returned.
    **kwargs
        For other keyword-only arguments, see the
        :ref:`ufunc docs <ufuncs.kwargs>`.
    
        .. versionadded:: 1.16
           Now handles ufunc kwargs
    
    Returns
    -------
    y : ndarray
        The matrix product of the inputs.
        This is a scalar only when both x1, x2 are 1-d vectors.
    
    Raises
    ------
    ValueError
        If the last dimension of `x1` is not the same size as
        the secon

In [74]:
ProdMat = np.matmul(A,B)
ProdMat

array([[455, 209, 321, 376, 172],
       [576, 253, 313, 326, 113],
       [491, 237, 471, 466, 312],
       [662, 291, 464, 782, 294],
       [401, 197, 426, 388, 283]])

In [76]:
#
dir(np)

['ALLOW_THREADS',
 'BUFSIZE',
 'CLIP',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'WRAP',
 '_CopyMode',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__git_version__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_builtins',
 '_distribut

In [ ]:
# Tarea :
# Leer/comprender/digerir/estudiar/practicar todas las funciones que componen al modulo numpy
# Asi como de sus submodulos

In [77]:
# Un objeto ndarray es mutable
# MOdifiquemos la ultima columna de ProdMat
ProdMat[:, -1] = np.nan
ProdMat

ValueError: cannot convert float NaN to integer

In [78]:
# MOdifiquemos el tipo de dato de cada elemento de ProdMat
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          like=None)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        ``__array__`` method returns an array, or any (nested) sequence.
        If object is a scalar, a 0-dimensional array containing object is
        returned.
    dtype : data-type, optional
        The desired data-type for the array. If not given, NumPy will try to use
        a default ``dtype`` that can represent the values (by applying promotion
        rules when necessary.)
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if ``__array__`` returns a copy, if obj is a nested
        sequence, or if a copy is needed to satisfy any of the other
        requirements (``dtype``, ``order``, e

In [79]:
ProdMat = np.array(ProdMat, dtype = float)
ProdMat

array([[455., 209., 321., 376., 172.],
       [576., 253., 313., 326., 113.],
       [491., 237., 471., 466., 312.],
       [662., 291., 464., 782., 294.],
       [401., 197., 426., 388., 283.]])

In [80]:
# MOdifiquemos la ultima columna de ProdMat
ProdMat[:, -1] = np.nan
ProdMat

array([[455., 209., 321., 376.,  nan],
       [576., 253., 313., 326.,  nan],
       [491., 237., 471., 466.,  nan],
       [662., 291., 464., 782.,  nan],
       [401., 197., 426., 388.,  nan]])

In [81]:
#
dir(np)

['ALLOW_THREADS',
 'BUFSIZE',
 'CLIP',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'WRAP',
 '_CopyMode',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__git_version__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_builtins',
 '_distribut

In [ ]:
# # Tipos de enteros
# 'int16',
#  'int32',
#  'int64',
#  'int8',

In [ ]:
# # Tipos de numeros punto flotante
# 'float128',
#  'float16',
#  'float32',
#  'float64',

In [82]:
# Benchmark sobre los tipos enteros
import time
for tipo in [np.int16, np.int32, np.int64, np.int8]:
  time_i = time.time()
  np.random.randint(0,20, size = 10**7, dtype = tipo).sum()
  time_f = time.time()
  print("Tipo de entero ", tipo)
  print("Tiempo de procesamiento ", time_f - time_i)
  print("\n" + "*"*100 + "\n")

Tipo de entero  <class 'numpy.int16'>
Tiempo de procesamiento  0.15176153182983398

****************************************************************************************************

Tipo de entero  <class 'numpy.int32'>
Tiempo de procesamiento  0.17340517044067383

****************************************************************************************************

Tipo de entero  <class 'numpy.int64'>
Tiempo de procesamiento  0.19019484519958496

****************************************************************************************************

Tipo de entero  <class 'numpy.int8'>
Tiempo de procesamiento  0.11758971214294434

****************************************************************************************************



In [ ]:
# Lecturas
# https://www.jldelafuenteoconnor.es/Libro98_ful_portada.pdf
# Aritmetica de punto flotante : IEEE 754


In [87]:
for tipoflotante in [np.float64, np.float128]:
  time_i = time.time()
  np.linalg.inv(np.array(np.random.chisquare(9, (10**4,10**4)), dtype = tipoflotante))
  time_f = time.time()
  print("Tipo de punto flotante ", tipoflotante)
  print("Tiempo de procesamiento ", time_f - time_i)
  print("\n" + "*"*100 + "\n")


Tipo de punto flotante  <class 'numpy.float64'>
Tiempo de procesamiento  93.08293437957764

****************************************************************************************************



TypeError: array type float128 is unsupported in linalg